import React, { forwardRef } from "react";

const Invoice = forwardRef(({
  billNo,
  customerName,
  customerPhone,
  customerId,
  items,
  extras,
  total,
  paidAmount,
  extraDiscount,
  paymentMode,
  profile
}, ref) => {

  const getSubtotal = () => items.reduce((s, i) => s + i.price * i.qty, 0);
  const getProductDiscount = () => items.reduce((s, i) => s + (i.price * i.qty * (i.discount || 0)) / 100, 0);
  const getGST = () => items.reduce((s, i) => {
    let price = i.price - (i.price * (i.discount || 0)) / 100;
    return s + (price * i.qty * (i.gst || 0)) / 100;
  }, 0);
  const getExtraTotal = () => extras.reduce((s, e) => s + e.amount, 0);
  const remaining = total - (Number(paidAmount) || 0);

  return (
    <div ref={ref} style={{
      maxWidth: "800px",
      margin: "0 auto",
      padding: "20px",
      fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
      background: "#fff",
      color: "#000",
      border: "1px solid #ccc",
      borderRadius: "8px"
    }}>
      <header style={{ textAlign: "center", marginBottom: "20px" }}>
        <h1 style={{ margin: 0, fontSize: "28px" }}>{profile?.name || "Your Business"}</h1>
        <p style={{ margin: "2px 0" }}>{profile?.address}</p>
        <p style={{ margin: "2px 0" }}>Phone: {profile?.phone || "N/A"} | Email: {profile?.email || "-"}</p>
        <p style={{ margin: "2px 0" }}>GSTIN: {profile?.gstin || "-"}</p>
      </header>

      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "20px" }}>
        <div><strong>Bill No:</strong> {billNo}</div>
        <div><strong>Date:</strong> {new Date().toLocaleDateString()}</div>
      </div>

      <div style={{ marginBottom: "20px" }}>
        <p><strong>Customer:</strong> {customerName || "-"}</p>
        <p><strong>Phone:</strong> {customerPhone || "-"}</p>
        <p><strong>ID:</strong> {customerId || "-"}</p>
        <p><strong>Payment:</strong> {paymentMode || "-"}</p>
      </div>

      <table style={{
        width: "100%",
        borderCollapse: "collapse",
        marginBottom: "20px"
      }}>
        <thead>
          <tr style={{ background: "#f4f4f4" }}>
            <th style={{ border: "1px solid #ccc", padding: "8px" }}>#</th>
            <th style={{ border: "1px solid #ccc", padding: "8px" }}>Product</th>
            <th style={{ border: "1px solid #ccc", padding: "8px" }}>Qty</th>
            <th style={{ border: "1px solid #ccc", padding: "8px" }}>Price</th>
            <th style={{ border: "1px solid #ccc", padding: "8px" }}>Discount</th>
            <th style={{ border: "1px solid #ccc", padding: "8px" }}>GST</th>
            <th style={{ border: "1px solid #ccc", padding: "8px" }}>Total</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item, i) => (
            <tr key={i}>
              <td style={{ border: "1px solid #ccc", padding: "8px" }}>{i + 1}</td>
              <td style={{ border: "1px solid #ccc", padding: "8px" }}>{item.name}</td>
              <td style={{ border: "1px solid #ccc", padding: "8px", textAlign: "center" }}>{item.qty}</td>
              <td style={{ border: "1px solid #ccc", padding: "8px" }}>₹{item.price.toFixed(2)}</td>
              <td style={{ border: "1px solid #ccc", padding: "8px", textAlign: "center" }}>{item.discount || 0}%</td>
              <td style={{ border: "1px solid #ccc", padding: "8px", textAlign: "center" }}>{item.gst || 0}%</td>
              <td style={{ border: "1px solid #ccc", padding: "8px" }}>₹{item.total.toFixed(2)}</td>
            </tr>
          ))}

          {extras.map((e, i) => (
            <tr key={`extra-${i}`} style={{ background: "#f9f9f9" }}>
              <td colSpan={6} style={{ border: "1px solid #ccc", padding: "8px" }}><strong>Extra: {e.name}</strong></td>
              <td style={{ border: "1px solid #ccc", padding: "8px", color: "green" }}>+₹{e.amount}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ textAlign: "right", marginBottom: "20px" }}>
        <p><strong>Subtotal:</strong> ₹{getSubtotal().toFixed(2)}</p>
        <p><strong>Discount:</strong> -₹{getProductDiscount().toFixed(2)}</p>
        <p><strong>GST:</strong> +₹{getGST().toFixed(2)}</p>
        <p><strong>Extra Discount:</strong> -₹{extraDiscount || 0}</p>
        <h2>Total: ₹{total.toFixed(2)}</h2>
        <p><strong>Paid:</strong> ₹{paidAmount || 0}</p>
        <p><strong>Remaining:</strong> <span style={{ color: remaining < 0 ? "red" : "green" }}>₹{remaining.toFixed(2)}</span></p>
      </div>

      <footer style={{ textAlign: "center", borderTop: "1px solid #ccc", paddingTop: "10px" }}>
        <p>Thank you!</p>
        <p>Generated by Tuljai Digital Ventures</p>
      </footer>
    </div>
  );
});

export default Invoice;